# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

formats: [html]

build:
  image: latest

  # Steps to build your Jupyter Book
  steps:
    - pip install -r docs/requirements.txt
    - jupyter-book build docs

python:
  version: 3.11
